# Generated by Django 4.2.1 on 2023-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('cat', models.IntegerField(choices=[(1, 'Fruits'), (2, 'Vegetables')], verbose_name='Category')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('status', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
